apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prometheus-migration-prometheus-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  glusterfs:
    endpoints: gluster-cluster
    path: /stage-k8s01-prometheus
