apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stage-k8s01-owncloud-storage
  namespace: owncloud
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 40Gi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: stage-k8s01-owncloud-mariadb
  volumeMode: Filesystem

