apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
spec:
  destination:
    name: ''
    namespace: owncloud
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 10.3.1
    chart: owncloud
    helm:
      valueFiles: []
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostname
          value: $STAGING_HOSTNAME
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false

