apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
spec:
  destination:
    name: ''
    namespace: owncloud
    server: 'https://kubernetes.default.svc'
  source:
    path: bitnami/owncloud
    repoURL: 'https://github.com/sommerit/bitnami-charts-fork/'
    targetRevision: HEAD
    helm:
      valueFiles: []
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostname
          value: owncloud.stage.sommerit.eu
        - name: persistence.enabled
          value: 'true'
        - name: persistence.size
          value: '40Gi'
        - name: persistence.existingClaim
          value: 'stage-k8s01-owncloud-storage'
        - name: mariadb.primary.persistence.existingClaim
          value: 'stage-k8s01-owncloud-mariadb'
        - name: ingress.tls
          value: 'false'
        - name: owncloudEmail
          value: "example@example.de"
        - name: service.type
          value: ClusterIP
        - name: ingress.pathType
          value: Prefix
        - name: ingress.path
          value: "/"
        - name: owncloudUsername
          value: "admin"
        - name: owncloudPassword
          value: "changeMe"
        - name: mariadb.auth.rootPassword
          value: "secretpassword"
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false

