apiVersion: v1
kind: PersistentVolume
metadata:
  name: stage-k8s01-owncloud-mariadb
  namespace: cachet
spec:
  capacity:
    storage: 10Gi
  glusterfs:
    endpoints: gluster-cluster
    path: /stage-k8s01-cachet
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

